# This file is only suitable to be used during development, not production.
# It only sets up and installs the packages. 
# The source will be mounted as a volume by Docker compose.

FROM node:18

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY --chown=node:node package.json .
RUN npm install --silent

COPY --chown=node:node . .
USER node