version: "3.8"

services:

  # api-backup:
  #   container_name: ${PROJECT_NAME?err}_api_db_backup
  #   image: databack/mysql-backup:${MYSQL_BACKUP_VERSION?err}
  #   environment:
  #     DB_SERVER: ${PROJECT_NAME?err}_api_db
  #     DB_USER: ${DB_USER?err}
  #     DB_PASS: ${DB_PASSWORD?err}
  #     DB_NAMES: ${DB_DATABASE?err}
  #     SINGLE_DATABASE: "true"
  #     DB_DUMP_TARGET: ${DB_BACKUP_TARGET?err}
  #     # # Uncomment for instant, one-time backup (will exit after upload)
  #     RUN_ONCE: "true"
  #     DB_DUMP_BEGIN: "0700"
  #     AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY?err}
  #     AWS_SECRET_ACCESS_KEY: ${S3_ACCESS_SECRET?err}
  #     AWS_DEFAULT_REGION: ${S3_REGION?err}
  #     # COMPRESSION: bzip2
  #     DB_DUMP_KEEP_PERMISSIONS: "false"
  #     NICE: "true"
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - api

  mysql-restore:
    container_name: ${PROJECT_NAME?err}_api_db_restore
    image: databack/mysql-backup:${MYSQL_BACKUP_VERSION?err}
    environment:
      DB_SERVER: ${PROJECT_NAME?err}_api_db
      DB_USER: ${DB_USER?err}
      DB_PASS: ${DB_PASSWORD?err}
      DB_NAMES: ${DB_DATABASE?err}
      SINGLE_DATABASE: "true"
      ## IMPORTANT: Update filename with intended restore ##
      DB_RESTORE_TARGET: ${DB_BACKUP_TARGET?err}/${DB_BACKUP_FILENAME?err}
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY?err}
      AWS_SECRET_ACCESS_KEY: ${S3_ACCESS_SECRET?err}
      AWS_DEFAULT_REGION: ${S3_REGION?err}
      # COMPRESSION: bzip2
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - api


networks:
  nginx:
    external: true
  api:
    name: ${PROJECT_NAME?err}_api
    external: true
