name: Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  astro:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: astro
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: astro/package-lock.json
      - run: npm ci
      - run: npm run build
